---
# The list of urls needed for API calls.
urls:
  price_api: https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH,XRP,BTC&tsyms=USD,INR
  post_api:
    slack: https://hooks.slack.com/services/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

configuration:
  type: schedule
  verbose: true
  parameters:
    frequency: 24 # in hours
...