---
# The list of urls needed for API calls.
urls:
  price_api: https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD
  post_api:
    slack: YOUR_SLACK_WEBHOOK

configuration:
  type: price_change
  verbose: true
  parameters:
    price_change: 5
    check_every_x_mins: 10

...